/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "SESAccessKeyId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SESSecretAccessKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SenderEmail": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "CloudflareAuth": cloudflare.Service
  }
}

import "sst"
export {}